[package]
name = "chat_server"
version = "0.0.1"
authors = ["Kirill <oskal174@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.rusqlite]
version = "0.17.0"
features = ["bundled"]
